swap MODS Sample Simple and Advanced for DSM 7.x

diff --git a/MODS Sample - Advanced CGI 7.x/scripts/common b/MODS Sample - Advanced CGI 7.x/scripts/common
--- a/MODS Sample - Advanced CGI 7.x/scripts/common
+++ b/MODS Sample - Advanced CGI 7.x/scripts/common
@@ -37,15 +37,6 @@ if [ -z $SYNOPKG_PKGNAME ]; then
 fi
 LOG="/tmp/$SYNOPKG_PKGNAME.log"
 ERR="/tmp/$SYNOPKG_PKGNAME.err"
-if [ ! -f $ERR ]; then
-	touch $ERR
-	chmod og+w $ERR
-fi
-if [ ! -f $LOG ]; then
-	touch $LOG
-	chmod og+w $LOG
-fi
-
 SEP="################################################################################################################################################################################"
 WIZARD=0
 
@@ -83,9 +74,63 @@ function ShowLog() {
 	fi
 }
 
+# Execute a command via SSH on the local host, using a php script
+function ExecSSH() {
+	user=$1	# Admin account
+	pass=$2	# Admin password
+	port=$3 # SSH port
+	cmd=$4	# Command to execute
+	
+	# Find the php version to be used 
+	version=`php -v | grep "PHP " | cut -f2 -d " "`
+	major=`echo $version | cut -d. -f1`
+	minor=`echo $version | cut -d. -f2`
+	
+	if [ $0 == "-sh" ]; then
+		# If run from a -sh, assume that the php script os local
+		path="."
+	else
+		path="/var/packages/$SYNOPKG_PKGNAME/scripts"
+	fi
+	script="$path/exec.php"
+		
+	# Call PHP with ssh2 modules
+	output="$(php -dextension=/var/packages/PHP$major.$minor/target/usr/local/lib/php$major$minor/modules/ssh2.so "$script" -u "$user" -p "$pass" -s "127.0.0.1" -o "$port" -c "$cmd")"
+	ExitCode=$? #Do not add any line or comment between the command and this line retrieving its exit code!!
+	
+	LogInfo "$output"
+	return $ExitCode
+}
+
+# Validate credentials to connect via SSH on the local host, using a php script
+function CheckSSH() {
+	user=$1	# Admin account
+	pass=$2	# Admin password
+	port=$3 # SSH port
+	
+	# Find the php version to be used 
+	version=`php -v | grep "PHP " | cut -f2 -d " "`
+	major=`echo $version | cut -d. -f1`
+	minor=`echo $version | cut -d. -f2`
+	
+	if [ $0 == "-sh" ]; then
+		# If run from a -sh, assume that the php script os local
+		path="."
+	else
+		path="/var/packages/$SYNOPKG_PKGNAME/scripts"
+	fi
+	script="$path/check.php"
+		
+	# Call PHP with ssh2 modules
+	output="$(php -dextension=/var/packages/PHP$major.$minor/target/usr/local/lib/php$major$minor/modules/ssh2.so "$script" -u "$user" -p "$pass" -s "127.0.0.1" -o "$port")"
+	ExitCode=$? #Do not add any line of comment between the command and this line retrieving its exit code!!
+
+	LogInfo "$output"
+	return $ExitCode
+}
+
 # Link nginx to the package's config file defined to be able to run php scripts outside to web root folder
 function LinkNginx() {
-	LogInfo "I am : `whoami`"
 	if [ -f $SYNOPKG_PKGDEST/ui/router.cgi ]; then
 		# Set the name of the package in the router cgi
 		sed -i -e "s|@SYNOPKG_PKGNAME@|$SYNOPKG_PKGNAME|g" "$SYNOPKG_PKGDEST/ui/router.cgi"
@@ -101,29 +146,83 @@ function LinkNginx() {
 		if [ -f $LINK ]; then
 			LogInfo "Link to nginx config already exists."
 		else
-			sudo /bin/ln -s "$SYNOPKG_PKGDEST/ui/dsm.cgi.conf" "$LINK"
+			# Check if SSH connection is working
+			LogInfo "Checking SSH credentials"
+			CheckSSH "$MODS_ADMIN" "$MODS_PASSWORD" "$MODS_PORT"
+			ExitCode=$? #Do not add any line of comment between the command and this line retrieving its exit code!!
+			
+			if [ $ExitCode == 0 ]; then
+			
+				# Store Admin account and SSH port
+				if [ ! -z $MODS_ADMIN ]; then
+					echo "MODS_ADMIN=$MODS_ADMIN" > "/var/packages/$SYNOPKG_PKGNAME/etc/parameters"
+					echo "MODS_PORT=$MODS_PORT" >> "/var/packages/$SYNOPKG_PKGNAME/etc/parameters"
+					chmod og-r "/var/packages/$SYNOPKG_PKGNAME/etc/parameters"
+				fi
+
+				# Store Admin password if requested
+				if [ $MODS_SAVE == "true" ]; then
+					# Create a Private Key to encrypt the password
+					if [ ! -f "/var/packages/$SYNOPKG_PKGNAME/etc/image" ]; then
+						LogInfo "Creating Encryption Key"
+						openssl genrsa -out /var/packages/$SYNOPKG_PKGNAME/etc/image 2048 2> /dev/null
+					fi
+					
+					# Encrypt and store the password
+					if [ ! -z $MODS_PASSWORD ]; then
+						LogInfo "Encrypting Password"
+						echo "$MODS_PASSWORD" | openssl rsautl -inkey /var/packages/$SYNOPKG_PKGNAME/etc/image -encrypt > /var/packages/$SYNOPKG_PKGNAME/etc/backup
+						chmod og-r /var/packages/$SYNOPKG_PKGNAME/etc/backup
+					fi
+				else
+					LogInfo "Don't store Password"
+				fi
+
+				# Create the Symbolic link
+				LogInfo "Creating nginx Link"
+				ExecSSH "$MODS_ADMIN" "$MODS_PASSWORD" "$MODS_PORT" "ln -s $SYNOPKG_PKGDEST/ui/dsm.cgi.conf $LINK"
+				ExitCode=$?
 				
-			# Check that the link has been created
-			if [ ! -f $LINK ]; then
+				# Check that the link has been created
+				if [ ! -f $LINK ]; then
+					PublishInfo ""
+					PublishInfo "Link Creation failed..."
+					PublishInfo "Investigate the reason in the Logs"		
+					exit 150
+				fi 	
+			else
+			
 				PublishInfo ""
-				PublishInfo "Link Creation failed..."
-				PublishInfo "Investigate the reason in the Logs"
-				return 1
-			fi 	
+				PublishInfo "Cannot connect via SSH onto the NAS with provided Login/Password."
+				PublishInfo "Go back into the Installation Wizard to change your Login/Password."
+				exit 150
+			fi
 		fi
 	fi
-	
-	return 0
 }
 
 # Unlink nginx config
 function UnlinkNginx() {
-	LogInfo "I am : `whoami`"
 	if [ $SYNOPKG_PKG_STATUS == "UNINSTALL" ]; then
 		LINK="/usr/syno/share/nginx/conf.d/dsm.$SYNOPKG_PKGNAME.conf"
 
 		if [ -f $LINK ]; then
-			sudo /bin/unlink "$LINK"
+			# Retrieve previous credentials if no account received from Wizard
+			if [ -z $MODS_ADMIN ] && [ -f /var/packages/$SYNOPKG_PKGNAME/etc/backup ]; then			
+				if [ -f /var/packages/$SYNOPKG_PKGNAME/etc/parameters ]; then			
+					. /var/packages/$SYNOPKG_PKGNAME/etc/parameters
+				fi
+
+				if [ -z $MODS_PASSWORD ]; then
+					LogInfo "Retrieving previous SSH credentials"
+					MODS_PASSWORD=$(openssl rsautl -inkey /var/packages/$SYNOPKG_PKGNAME/etc/image -decrypt < /var/packages/$SYNOPKG_PKGNAME/etc/backup)			
+				fi
+			fi
+			
+			# Unlink nginx configuration
+			LogInfo "Removing nginx Link"
+			ExecSSH "$MODS_ADMIN" "$MODS_PASSWORD" "$MODS_PORT" "unlink $LINK"
+			ExitCode=$?
 			
 			if [ -f $LINK ]; then
 				PublishInfo
